# Generated by Django 5.1.2 on 2025-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acceptance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataforanalysis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
